services:
  api:
    image: golang:1.24
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "2000:2000"
    env_file:
      - .env
    restart: always
    networks:
      - servicenet

networks:
  servicenet:
    external: true
